// This file is auto-generated by @hey-api/openapi-ts

export type GetUploadsData = {
    query?: {
        page_size?: unknown;
        page_token?: unknown;
        user_id?: unknown;
    };
};

export type GetUploadsResponse = ({
    uploads: Array<{
        id: string;
        createdAt: string;
        updatedAt: (string) | null;
        fileName: string;
        filePath: string;
        fileSize: number;
        fileType: string;
        userId: string;
        user: {
            id: string;
            createdAt: string;
            updatedAt: (string) | null;
            username: string;
        };
    }>;
    next_page_token?: string;
});

export type GetUploadsError = unknown;

export type GetUploadData = {
    path: {
        upload_id: unknown;
    };
};

export type GetUploadResponse = ({
    upload: {
        id: string;
        createdAt: string;
        updatedAt: (string) | null;
        fileName: string;
        filePath: string;
        fileSize: number;
        fileType: string;
        userId: string;
        user: {
            id: string;
            createdAt: string;
            updatedAt: (string) | null;
            username: string;
        };
    };
});

export type GetUploadError = (unknown);